services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: main
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: